version: '3.8'

services:
  firefly_iii_app:
    image: 'fireflyiii/core:latest'
    restart: unless-stopped
    environment:
      - FF_DB_HOST=firefly_iii_db
      - FF_DB_PORT=3307  # Cambia este valor al puerto que desees usar
      - FF_DB_DATABASE=firefly
      - FF_DB_USER=firefly
      - FF_DB_PASSWORD=firefly
      - FF_APP_KEY=SomeRandomStringOf32CharsExactly
      - FF_APP_ENV=local
    volumes:
      - ./firefly_iii_export:/var/www/firefly-iii/storage/export
      - ./firefly_iii_upload:/var/www/firefly-iii/storage/upload
    depends_on:
      - firefly_iii_db

  firefly_iii_db:
    image: 'mariadb:latest'
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=firefly
      - MYSQL_DATABASE=firefly
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=firefly
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3307:3306  # Asegúrate de cambiar este valor al mismo puerto que especificaste arriba
