version: '3.9'  

services:

  firefly-iii:
    image: firefly-iii/firefly-iii:latest
    restart: unless-stopped
    ports:
      - "8700:8700" 
    environment:
      - FIREFLY_DB_DRIVER : mysql
      - FIREFLY_DB_HOST : mariadb  
      - FIREFLY_DB_NAME : firefly  
      - FIREFLY_DB_USER : ${MYSQL_USER} 
      - FIREFLY_DB_PASSWORD : ${MYSQL_PASSWORD}
      - FIREFLY_WEB_SERVER : nginx 
      # - FIREFLY_LOG_LEVEL=debug

  mariadb:
    image: mariadb:10.6  
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/mysql 
    environment:
      - MYSQL_ROOT_PASSWORD : ${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE : ${MYSQL_DATABASE}
      - MYSQL_USER : ${MYSQL_USER}  
      - MYSQL_PASSWORD : ${MYSQL_PASSWORD}  

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "8180:80" 
    depends_on:
      - mariadb  
    environment:
      - MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      - PMA_USER: ${MYSQL_USER}
      - PMA_PASSWORD: ${MYSQL_PASSWORD}
